# Copyright (C) 2026 Sutura Authors
# SPDX-License-Identifier: Apache-2.0
"""Backward-compatibility shim for sutura.triage.

Re-exports all functionality from sutura_engine.triage.
"""
from sutura_engine.triage import (
    LadderEntry,
    INTENSITIES,
    DEFAULT_INTENSITY,
    INTENSITY_ENV,
    INTENSITY_CONFIG,
    PROFILES_CONFIG,
    PROFILES_SCHEMA_VERSION,
    HAUSDORFF_FLOOR,
    DEEP_REPAIR_MODES,
    IntensitySpec,
    PRESETS,
    _PROFILE_FIELDS,
    _warn,
    _coerce_ladder,
    _coerce_field,
    _normalize_entry,
    _build_spec,
    name_error,
    unique_profile_name,
    rename_profile,
    duplicate_profile,
    load_profiles,
    save_profiles,
    resolve_intensity_detail,
    resolve_intensity,
    effective_spec,
    list_intensities,
    triage_report_fields,
    format_intensities,
    profile_overrides,
    # Execution policy
    AUTO_MAX_ATTEMPTS,
    AUTO_FALLBACK_BUDGET_FACTOR,
    AUTO_FALLBACK_MIN_S,
    AUTO_FALLBACK_MAX_S,
    AUTO_INVENT_MIN_SCORE,
    GENERATIVE_MAX_HAUSDORFF_REL,
    repair_with_methods,
)

__all__ = [
    'LadderEntry',
    'INTENSITIES',
    'DEFAULT_INTENSITY',
    'INTENSITY_ENV',
    'INTENSITY_CONFIG',
    'PROFILES_CONFIG',
    'PROFILES_SCHEMA_VERSION',
    'HAUSDORFF_FLOOR',
    'DEEP_REPAIR_MODES',
    'IntensitySpec',
    'PRESETS',
    '_PROFILE_FIELDS',
    '_warn',
    '_coerce_ladder',
    '_coerce_field',
    '_normalize_entry',
    '_build_spec',
    'name_error',
    'unique_profile_name',
    'rename_profile',
    'duplicate_profile',
    'load_profiles',
    'save_profiles',
    'resolve_intensity_detail',
    'resolve_intensity',
    'effective_spec',
    'list_intensities',
    'triage_report_fields',
    'format_intensities',
    'profile_overrides',
    'AUTO_MAX_ATTEMPTS',
    'AUTO_FALLBACK_BUDGET_FACTOR',
    'AUTO_FALLBACK_MIN_S',
    'AUTO_FALLBACK_MAX_S',
    'AUTO_INVENT_MIN_SCORE',
    'GENERATIVE_MAX_HAUSDORFF_REL',
    'repair_with_methods',
]
